
package abc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ITestService", targetNamespace = "http://demows03.example.com/", wsdlLocation = "http://localhost:8080/demoWS03-1.0-SNAPSHOT/services/TestService?wsdl")
public class ITestService_Service
    extends Service
{

    private final static URL ITESTSERVICE_WSDL_LOCATION;
    private final static WebServiceException ITESTSERVICE_EXCEPTION;
    private final static QName ITESTSERVICE_QNAME = new QName("http://demows03.example.com/", "ITestService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/demoWS03-1.0-SNAPSHOT/services/TestService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ITESTSERVICE_WSDL_LOCATION = url;
        ITESTSERVICE_EXCEPTION = e;
    }

    public ITestService_Service() {
        super(__getWsdlLocation(), ITESTSERVICE_QNAME);
    }

    public ITestService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ITESTSERVICE_QNAME, features);
    }

    public ITestService_Service(URL wsdlLocation) {
        super(wsdlLocation, ITESTSERVICE_QNAME);
    }

    public ITestService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ITESTSERVICE_QNAME, features);
    }

    public ITestService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ITestService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ITestService
     */
    @WebEndpoint(name = "TestServicePort")
    public ITestService getTestServicePort() {
        return super.getPort(new QName("http://demows03.example.com/", "TestServicePort"), ITestService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ITestService
     */
    @WebEndpoint(name = "TestServicePort")
    public ITestService getTestServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://demows03.example.com/", "TestServicePort"), ITestService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ITESTSERVICE_EXCEPTION!= null) {
            throw ITESTSERVICE_EXCEPTION;
        }
        return ITESTSERVICE_WSDL_LOCATION;
    }

}
