# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mydata.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'mydata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmydata.proto\x12\x04\x64\x61ta\"\x8a\x01\n\x06MyData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05items\x18\x03 \x03(\t\x12(\n\x06values\x18\x04 \x03(\x0b\x32\x18.data.MyData.ValuesEntry\x1a-\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x42#\n\x14org.example.protobufB\x0bMyDataProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mydata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024org.example.protobufB\013MyDataProto'
  _globals['_MYDATA_VALUESENTRY']._loaded_options = None
  _globals['_MYDATA_VALUESENTRY']._serialized_options = b'8\001'
  _globals['_MYDATA']._serialized_start=23
  _globals['_MYDATA']._serialized_end=161
  _globals['_MYDATA_VALUESENTRY']._serialized_start=116
  _globals['_MYDATA_VALUESENTRY']._serialized_end=161
# @@protoc_insertion_point(module_scope)
