
package springws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorPortType", targetNamespace = "http://ws.par.wsb/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorPortType {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://ws.par.wsb/", className = "springws.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://ws.par.wsb/", className = "springws.HelloResponse")
    public String hello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param number1
     * @param number2
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://ws.par.wsb/", className = "springws.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ws.par.wsb/", className = "springws.AddResponse")
    public int add(
        @WebParam(name = "number1", targetNamespace = "")
        int number1,
        @WebParam(name = "number2", targetNamespace = "")
        int number2);

}
