version: '3.8'

services:
  # Warstwa Logiki Biznesowej (Backend API)
  backend:
    build: ./backend
    # build: ./backend-node
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/tododb
    depends_on:
      - db

  # Warstwa Danych (Baza Danych)
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  

  # Warstwa Prezentacji (Frontend)
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres-data: